version: '3.7'
services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    restart: always
    env_file: ./.env
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d auth -U app"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"

  redis:
    container_name: redis
    image: redis:alpine

  auth:
    container_name: auth
    build: ./auth
    env_file: ./.env
    volumes:
      - static:/auth/src/static
    expose:
      - "8001"
    depends_on:
      db:
        condition: service_healthy


  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:latest
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_conf/configs:/etc/nginx/conf.d:ro
      - ./auth/src/static:/static
    ports:
      - "80:80"
    depends_on:
      - auth

volumes:
  static: