version: '3.7'
services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    restart: always
    env_file: ./.env
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data/
      - ./db/restore/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
    - 5432:5432
    expose:
      - "5432"

  redis:
    container_name: redis
    image: redis:alpine
    ports:
    - 6379:6379

#  auth:
#    container_name: auth
#    build: ./auth
#    env_file: ./.env
#    expose:
#      - "8001"
#    depends_on:
#      - redis
#      - db

#  nginx:
#    container_name: dev_web
#    restart: on-failure
#    image: nginx:latest
#    volumes:
#      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx_conf/configs:/etc/nginx/conf.d:ro
#    ports:
#      - "80:80"
#    depends_on:
#      - auth
